config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'

  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :gplayers
  resources :goals
  resources :games #, :except => :show
  resources :players
  resources :goalies

end

app/models/goalie.rb
class Goalie < ActiveRecord::Base
  has_many :player_associations

  has_many :game_goalie_scores, :through => :player_associations
  has_many :season_goalie_scores, :through => :player_associations
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_many :player_associations

  has_many :game_scores, :through => :player_associations
  has_many :game_player_scores, :through => :player_associations
  has_many :season_player_scores, :through => :player_associations
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if
    session[:user_id]
  end

  def require_user
    redirect_to '/login' unless current_user
  end

end

app/controllers/goalies_controller.rb
class GoaliesController < ApplicationController
before_action :require_user, only: [:edit, :update, :destroy, :new, :create]
  def index
    @goalies = Goalie.all
  end

  def show
  end

  def edit
    @goalie = Goalie.find(params[:id])
  end

  def update
    @goalie = Goalie.find(params[:id])

    if @goalie.update(goalie_params)
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def new
  end

  def create
    @goalie = Goalie.create(goalie_params)

    if @goalie.save
      redirect_to root_url
    else
      render 'new'
    end
  end

  def destroy
    @goalie = Goalie.find(params[:id])
    @goalie.destroy

    redirect_to root_url
  end

  private
    def goalie_params
      params.require(:goalie).permit(:name, :games, :saves, :assists, :wins, :ties, :losses)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @players = Player.all
    @goalies = Goalie.all
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :require_user, only: [:edit, :update, :destroy, :new, :create]

  def index
    @players = Player.all
  end

  def show
  end

  def edit
    @player = Player.find(params[:id])
  end

  def update
    @player = Player.find(params[:id])

    if @player.update(player_params)
      redirect_to root_url
    else
      render 'edit'
    end
  end

  def new
  end

  def create
    @player = Player.create(player_params)

    if @player.save
      redirect_to root_url, :notice => "Pelaaja luotu!"
    else
      render 'new'
    end
  end

  def destroy
    @player = Player.find(params[:id])
    @player.destroy

    redirect_to root_url
  end

  private
    def player_params
      params.require(:player).permit(:name, :games, :goals, :points, :assists, :plus, :minus, :vom)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  layout 'login_layout'
  def new
  end

  def create
    @user = User.find_by_username(params[:session][:username])
      if @user && @user.authenticate(params[:session][:password])
        session[:user_id] = @user.id
        redirect_to '/'
      else
        render action: 'new', alert: "Väärät tunnukset"
      end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goalies_helper.rb
module GoaliesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/goalies/edit.html.erb
<h1> Muokkaa maalivahtia </h1>
<%= form_for(@goalie) do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Nimi' %>
    <%= f.text_field(:name, class: "form-control") %>
  </div>
  <div class="form-group">
    <%= f.label :games, 'Pelit' %>
    <%= f.text_field(:games, class: "form-control")%>
  </div>
  <div class="form-group">
    <%= f.label :saves, 'Torjunnat' %>
    <%= f.text_field(:saves, class: "form-control")%>
  </div>
  <div class="form-group">
    <%= f.label :assists, 'Syötöt' %>
    <%= f.text_field(:assists, class: "form-control")%>
  </div>
  <div class="form-group">
    <%= f.label :wins, 'Voitot' %>
    <%= f.text_field(:wins, class: "form-control")%>
  </div>
  <div class="form-group">
    <%= f.label :ties, 'Tasurit' %>
    <%= f.text_field(:ties, class: "form-control")%>
  </div>
  <div class="form-group">
    <%= f.label :losses, 'Häviöt' %>
    <%= f.text_field(:losses, class: "form-control")%>
  </div>
  <%= f.submit "Muokkaa", class: "btn btn-primary" %>
  <%= link_to "Poista", goaly_path(@goalie), method: :delete, class: "btn btn-danger" %>
  <%= link_to 'Takaisin', root_path %>

<% end %>

app/views/goalies/index.html.erb
<h1 style="text-align: center"> Maalivahdit </h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nimi</th>
      <th>Pelit</th>
      <th>Torjunnat</th>
      <th>Syötöt</th>
      <th>Voitot</th>
      <th>Tasapelit</th>
      <th>Häviöt</th>
    </tr>
  </thead>
  <% @goalies.each do |g| %>
  <tr>
    <th><%= g.name %></th>
    <th><%= g.games %></th>
    <th><%= g.saves %></th>
    <th><%= g.assists %></th>
    <th><%= g.wins %></th>
    <th><%= g.ties %></th>
    <th><%= g.losses %></th>
    <% if current_user %>
    <th><%= link_to "Muokkaa", edit_goaly_path(g) %></th>
    <% end %>
  </tr>
  <% end %>
</table>

app/views/goalies/new.html.erb
<h1> Lisää maalivahti </h1>
<%= form_for(:goalie, url: goalies_path) do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Nimi' %>
    <%= f.text_field(:name, class: "form-control") %>
  </div>
  <div class="form-group">
    <%= f.label :games, 'Pelit' %>
    <%= f.text_field(:games, class: "form-control")%>
  </div>
  <div class="form-group">
    <%= f.label :saves, 'Torjunnat' %>
    <%= f.text_field(:saves, class: "form-control")%>
  </div>
  <div class="form-group">
    <%= f.label :assists, 'Syötöt' %>
    <%= f.text_field(:assists, class: "form-control")%>
  </div>
  <div class="form-group">
    <%= f.label :wins, 'Voitot' %>
    <%= f.text_field(:wins, class: "form-control")%>
  </div>
  <div class="form-group">
    <%= f.label :ties, 'Tasurit' %>
    <%= f.text_field(:ties, class: "form-control")%>
  </div>
  <div class="form-group">
    <%= f.label :losses, 'Häviöt' %>
    <%= f.text_field(:losses, class: "form-control")%>
  </div>
  <%= f.submit "Luo maalivahti", class: "btn btn-primary" %>
  <%= link_to 'Takaisin', root_path %>

<% end %>

app/views/goalies/show.html.erb
<h1 style="text-align: center"> Maalivahti </h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nimi</th>
      <th>Pelit</th>
      <th>Torjunnat</th>
      <th>Syötöt</th>
      <th>Voitot</th>
      <th>Tasurit</th>
      <th>Häviöt</th>
    </tr>
  </thead>
  <% p = @goalie %>
  <tr>
    <th><%= p.name %></th>
    <th><%= p.games %></th>
    <th><%= p.saves %></th>
    <th><%= p.assists %></th>
    <th><%= p.wins %></th>
    <th><%= p.ties %></th>
    <th><%= p.losses %></th>
    <th><%= link_to "Muokkaa", edit_goaly_path(@goalie) %></th>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pokeporssi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <nav class="navbar navbar-default">
    <div class="container-fluid">

    <div class="navbar-header">
      <a class="navbar-brand" href="/">POKE</a>
    </div>
<% if current_user %>
<ul class="navbar-form navbar-left">
  <button class="btn btn-primary navbar-btn">
    <%= link_to "Uusi pelaaja", new_player_path %>
  </button>
  <button class="btn btn-primary navbar-btn">
    <%= link_to "Uusi maalivahti", new_goaly_path %>
  </button>

</ul>
  <ul class="navbar-form navbar-right">
    <button class="btn btn-default navbar-btn"> <%= link_to "Kirjaudu ulos", logout_path, method: "delete" %></button>
  </ul>
<% end %>
  </nav>
</head>
<body>



  <div id="main-container" class="container">
    <div class="row">
      <div class="col-xs-3">
        <ul>
          <li><%= link_to "Etusivu", root_url %></li>
        </ul>
      </div>
      <div class="col-xs-9">
        <%= yield %>
      </div>
    </div>
  </div>



</body>
</html>

app/views/layouts/login_layout.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pokeporssi</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <nav class="navbar navbar-default">
    <div class="container-fluid">

    <div class="navbar-header">
      <a class="navbar-brand" href="/">POKE</a>
    </div>
<% if current_user %>
  <ul class="navbar-form navbar-right">

    <button class="btn btn-default navbar-btn"> <%= link_to "Kirjaudu ulos", logout_path, method: "delete" %></button>
  </ul>
<% end %>
  </nav>
</head>
<body>



  <div id="main-container" class="container">
    <div class="row">
      <div class="col-xs-3">

      </div>
      <div class="col-xs-6">
        <%= yield %>
      </div>
      <div class="col-xs-3">

      </div>
    </div>
  </div>



</body>
</html>

app/views/pages/index.html.erb
<h1 style="text-align: center"> ALL TIME PISTEPÖRSSI </h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nimi</th>
      <th>Pelit</th>
      <th>Maalit</th>
      <th>Pisteet</th>
      <th>Syötöt</th>
      <th>+</th>
      <th>-</th>
      <th>VOM</th>
    </tr>
  </thead>
  <% @players.order("points desc").each do |p| %>
  <tr>
    <th><%= p.name %></th>
    <th><%= p.games %></th>
    <th><%= p.goals %></th>
    <th><%= p.points %></th>
    <th><%= p.assists %></th>
    <th><%= p.plus %></th>
    <th><%= p.minus %></th>
    <th><%= p.vom %></th>
    <% if current_user %>
    <th><%= link_to "Muokkaa", edit_player_path(p) %></th>
    <% end %>
  </tr>
  <% end %>
</table>

<h1 style="text-align: center"> Goalies </h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nimi</th>
      <th>Pelit</th>
      <th>Torjunnat</th>
      <th>Syötöt</th>
      <th>Voitot</th>
      <th>Tasurit</th>
      <th>Häviöt</th>
    </tr>
  </thead>
  <% @goalies.each do |g| %>
  <tr>
    <th><%= g.name %></th>
    <th><%= g.games %></th>
    <th><%= g.saves %></th>
    <th><%= g.assists %></th>
    <th><%= g.wins %></th>
    <th><%= g.ties %></th>
    <th><%= g.losses %></th>
    <% if current_user %>
    <th><%= link_to "Muokkaa", edit_goaly_path(g) %></th>
    <% end %>
  </tr>
  <% end %>
</table>

app/views/players/edit.html.erb
<h1> Muokkaa pelaajaa </h1>
<%= form_for(@player) do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Nimi' %>
    <%= f.text_field(:name, class: "form-control") %>
  </div>
  <div class="form-group">
    <%= f.label :games, 'Pelit' %>
    <%= f.text_field(:games, class: "form-control")%>
  </div>
  <div class="form-group">
    <%= f.label :goals, 'Maalit' %>
    <%= f.text_field(:goals, class: "form-control")%>
  </div>
  <div class="form-group">
    <%= f.label :points, 'Pisteet' %>
    <%= f.text_field(:points, class: "form-control")%>
  </div>
  <div class="form-group">
    <%= f.label :assists, 'Syötöt' %>
    <%= f.text_field(:assists, class: "form-control")%>
  </div>
  <div class="form-group">
    <%= f.label :plus, '+' %>
    <%= f.text_field(:plus, class: "form-control")%>
  </div>
  <div class="form-group">
    <%= f.label :minus, '-' %>
    <%= f.text_field(:minus, class: "form-control")%>
  </div>
  <div class="form-group">
    <%= f.label :vom, 'VOM' %>
    <%= f.text_field(:vom, class: "form-control")%>
  </div>
  <%= f.submit "Muokkaa", class: "btn btn-primary" %>
  <%= link_to "Poista", player_path(@player), method: :delete, class: "btn btn-danger" %>
  <%= link_to 'Takaisin', root_path %>

<% end %>

app/views/players/index.html.erb
<h1 style="text-align: center"> ALL TIME PISTEPÖRSSI </h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nimi</th>
      <th>Pelit</th>
      <th>Maalit</th>
      <th>Pisteet</th>
      <th>Syötöt</th>
      <th>+</th>
      <th>-</th>
      <th>VOM</th>
    </tr>
  </thead>
  <% @players.order("points desc").each do |p| %>
  <tr>
    <th><%= p.name %></th>
    <th><%= p.games %></th>
    <th><%= p.goals %></th>
    <th><%= p.points %></th>
    <th><%= p.assists %></th>
    <th><%= p.plus %></th>
    <th><%= p.minus %></th>
    <th><%= p.vom %></th>
    <% if current_user %>
    <th><%= link_to "Muokkaa", edit_player_path(p) %></th>
    <% end %>
  </tr>
  <% end %>
</table>

app/views/players/new.html.erb
<h1> Luo pelaaja </h1>

<%= form_for :player, url: players_path do |f| %>
  <div class="form-group">
    <%= f.label :name, 'Nimi' %>
    <%= f.text_field(:name, class: "form-control") %>
  </div>
  <div class="form-group">
    <%= f.label :games, 'Pelit' %>
    <%= f.text_field(:games, class: "form-control", :value => '0')%>
  </div>
  <div class="form-group">
    <%= f.label :goals, 'Maalit' %>
    <%= f.text_field(:goals, class: "form-control", :value => '0')%>
  </div>
  <div class="form-group">
    <%= f.label :points, 'Pisteet' %>
    <%= f.text_field(:points, class: "form-control", :value => '0')%>
  </div>
  <div class="form-group">
    <%= f.label :assists, 'Syötöt' %>
    <%= f.text_field(:assists, class: "form-control", :value => '0')%>
  </div>
  <div class="form-group">
    <%= f.label :plus, '+' %>
    <%= f.text_field(:plus, class: "form-control", :value => '0')%>
  </div>
  <div class="form-group">
    <%= f.label :minus, '-' %>
    <%= f.text_field(:minus, class: "form-control", :value => '0')%>
  </div>
  <div class="form-group">
    <%= f.label :vom, 'VOM' %>
    <%= f.text_field(:vom, class: "form-control", :value => '0')%>
  </div>
  <%= f.submit "Lisää pelaaja", class: "btn btn-primary" %>
  <%= link_to "Takaisin", root_path %>

<% end %>

app/views/players/show.html.erb
<h1 style="text-align: center"> ALL TIME PISTEPÖRSSI </h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Nimi</th>
      <th>Pelit</th>
      <th>Maalit</th>
      <th>Pisteet</th>
      <th>Syötöt</th>
      <th>+</th>
      <th>-</th>
      <th>VOM</th>
    </tr>
  </thead>
  <% p = @player %>
  <tr>
    <th><%= p.name %></th>
    <th><%= p.games %></th>
    <th><%= p.goals %></th>
    <th><%= p.points %></th>
    <th><%= p.assists %></th>
    <th><%= p.plus %></th>
    <th><%= p.minus %></th>
    <th><%= p.vom %></th>
    <th><%= link_to "Muokkaa", edit_player_path(@player) %></th>
  </tr>
</table>